### PR TITLE
Dockerize application

### PR DESCRIPTION
**Pull request by bigdoods**
- Refactor so that all application configs are available from one location
- Dockerfile and docker-compose for application
- Update quick start guide in README

Notes:
- [ ] Test if working with mongo running on localhost
- [ ] Test if working with mongo hosted.

### CODE REVIEW

**Comment by didimitrie** [comment]
I'm digging this. I think docker is a good option (sloooowly getting there, don't shoot!) . I'll give it a spin locally. Have some qualms re naming of things, but this should be good. 

Also test case reminder: full workflow w/h digital ocean (ie, spin up droplet, get docker, get speckle, run, and see if it works). 

Should we also start thinking of a little init script to help out? no idea how to approach this, but just ran through the install process of discourse and i dig it. Fairly complex app, but just asks you a few questions at the beginning and afterwards you're ready to go, ie: 
- what's your db uri
- server name

For later:
- let's encrypt? or enforcing some https? this would be brilliant (ws fails a lot if unencrypted due to firewalls, proxys etc) - though it would mean adding nginx to the pile + hassle of ufw configs, etc.

Can't wait to test it and get this ironed out, then give people power to spin up this easily anywhere!

**Comment by didimitrie** [comment]
also for the future:

since we're dockerinzing stuff - which is great i actually realise now - then the install process can become simple regardless of the complexity behind. which means that we could allow for horizontal scaling at least to happen by: 

- using a redis layer for real time events between workers
- spinning the main rest api on as many cores as we have 

**Question more for the present:** 
monitoring and ensuring restart on fail? does this happen in this instance? I am always starting up my instances with pm2, so on app crash it will restart it as well as on a server/vm reboot it should pop again

**Comment by bigdoods** [comment]
The Jenca web client offers 
- https support (forced for all clients)
- websockets enabled (via nginx)
- scales application to use available resources on the host (multi-host scaling coming)
- monitoring tools for running application in production
- can use restart policies on containers. I will include and open new PR for this.

I will place Speckle on jenca so you can see this all in action I think :-)

**Comment by didimitrie** [comment]
Would actually be nice to have a second testing server! So people get the idea :)

**Pull request merged**
